/* REMEMBER TO REPLACE FOREIGN KEYS WITH YOUR OWN GENERATED FOREIGN KEYS*/
CREATE DATABASE conversation_db;
CREATE TABLE restaurant(
restaurant_uid uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
restaurant_name VARCHAR(255) NOT NULL
);
INSERT INTO restaurant(restaurant_name) VALUES('P.F. Chang''s');
INSERT INTO restaurant(restaurant_name) VALUES('Taco Bell');
INSERT INTO restaurant(restaurant_name) VALUES('McDonald''s');

CREATE TABLE menu(
restaurant_uid uuid REFERENCES restaurant(restaurant_uid) NOT NULL,
menu_uid uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
menu_name VARCHAR(255) NOT NULL
);

INSERT INTO menu(restaurant_uid,menu_name) VALUES('4cd7b6c8-426e-4912-adcd-627533dba9d3','PF1');
INSERT INTO menu(restaurant_uid,menu_name) VALUES('4cd7b6c8-426e-4912-adcd-627533dba9d3','PF2');
INSERT INTO menu(restaurant_uid,menu_name) VALUES('4537cb56-314a-4316-b7ae-29d11bc290c7','TB1');
INSERT INTO menu(restaurant_uid,menu_name) VALUES('4537cb56-314a-4316-b7ae-29d11bc290c7','TB2');
INSERT INTO menu(restaurant_uid,menu_name) VALUES('7abc1f9d-981e-47e1-b287-b9fbdbe08f37','McD1');
INSERT INTO menu(restaurant_uid,menu_name) VALUES('7abc1f9d-981e-47e1-b287-b9fbdbe08f37','McD2');

CREATE TABLE menu_items(
  restaurant_uid uuid REFERENCES restaurant(restaurant_uid) NOT NULL,
  item_uid uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  menu_uid uuid REFERENCES menu(menu_uid) NOT NULL,
  name VARCHAR(50) NOT NULL,
  price numeric NOT NULL,
  img VARCHAR(500) NOT NULL,
  description TEXT,
  ingredients TEXT,
  allergen_1 VARCHAR(50),
  allergen_2 VARCHAR(50), 
  allergen_3 VARCHAR(50), 
  allergen_4 VARCHAR(50), 
  allergen_5 VARCHAR(50)   
);

INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4cd7b6c8-426e-4912-adcd-627533dba9d3','1cf5b5f3-4c8b-4411-bf86-a7f67799d06b','Chang''s Chicken Lettuce Wraps',11.50,'https://www.pfchangs.com/images/default-source/menu/appetizers/chickenlettucewraps-1200x8005a84a633-b490-4ae4-a83a-b5f7bdf8660f.jpg?sfvrsn=6737f550_3','A secret family recipe and our signature dish. Enough said.','Minced Chicken,  Garlic, Scallion, Sesame Oil, Iceberg Lettuce, Kwispy Rice Sticks, Lime Wedge');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4cd7b6c8-426e-4912-adcd-627533dba9d3','1cf5b5f3-4c8b-4411-bf86-a7f67799d06b','BBQ Pork Spare Ribs',12.50,'https://www.pfchangs.com/images/default-source/menu/appetizers/bbqspareribs-1200x80046c1edd2-0747-4dba-872d-2ce45e317770.jpg?sfvrsn=92f03c0c_3','Slow-braised pork ribs with a tangy Asian barbecue sauce, smoked tableside','Pork Ribs, Garlic, Cole Slaw, Asian BBQ Sauce');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4cd7b6c8-426e-4912-adcd-627533dba9d3','1cf5b5f3-4c8b-4411-bf86-a7f67799d06b','Edamame',7.00,'https://www.pfchangs.com/images/default-source/menu/appetizers/edamame-1200x800dbef9f14-40fc-4cdc-a6ad-ea230154975d.jpg?sfvrsn=d42cf959_3','Steamed to order, tossed with kosher salt','Edamame, Kosher Salt, Chili Sauce');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4cd7b6c8-426e-4912-adcd-627533dba9d3','e9ea932c-65a7-455e-a890-29e35cde80e7','Tempura Calamari',11.00,'https://www.pfchangs.com/images/default-source/menu/appetizers/tempura-calamari08447429-b6dd-4129-ae55-d83d76f1f92d.jpg?sfvrsn=a1496a8d_3','Crisp calamari, hunan salt, wasabi aioli dipping sauce','Calamari, Hunan Salt, Wasabi Aioli');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4cd7b6c8-426e-4912-adcd-627533dba9d3','e9ea932c-65a7-455e-a890-29e35cde80e7','Kung Pao Brussels Sprouts',8.00,'https://www.pfchangs.com/images/default-source/menu/appetizers/kungpaobrusselssprouts-1200x8002018edae-dfc9-482d-a292-01d813e68bb2.jpg?sfvrsn=7338016c_3','Wok-charred Brussels sprouts, peanuts, chili pods, Kung Pao sauce','Brussels Sprouts, Peanuts, Chili Pods, Kung Pao Sauce');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4cd7b6c8-426e-4912-adcd-627533dba9d3','e9ea932c-65a7-455e-a890-29e35cde80e7','Dynamite Shrimp',12.00,'https://www.pfchangs.com/images/default-source/menu/appetizers/dynamiteshrimp-1200x800471afeff-6d74-45fa-9d79-c2c69b320326.jpg?sfvrsn=ee576309_3','Tempura-battered, tossed with a sriracha aioli','Shrimp, Tempura, Chives, Kwispy Rice Sticks, Romaine Lettuce,Sriracha aioli');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4537cb56-314a-4316-b7ae-29d11bc290c7','cfe8cf1c-54e5-4f58-a0f4-09d16f8b169a','Double Steak Grilled Cheese Burrito',5.49,'https://www.tacobell.com/images/23194_double_steak_grilled_cheese_burrito_classic_269x269.jpg','Double the steak*, nacho cheese sauce, seasoned rice, red strips, creamy chipotle sauce, reduced-fat sour cream, and three-cheese blend wrapped inside a warm flour tortilla, with even more three-cheese blend grilled on the top.','Steak, Nacho Cheese Sauce, Reduced Fat Sour Cream, Seasoned Rice, Chipolte Sauce, 3 Cheese Blend, Red Strips');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4537cb56-314a-4316-b7ae-29d11bc290c7','cfe8cf1c-54e5-4f58-a0f4-09d16f8b169a','Nachos BellGrande',3.99,'https://www.tacobell.com/images/22502_nachos_bellgrande_269x269.jpg','The Nachos BellGrande® includes a portion of crispy tortilla chips topped with warm nacho cheese sauce, refried beans, seasoned beef, ripe tomatoes and cool reduced fat sour cream.','Seasoned Beef, Nacho Cheese Sauce, Reduced Fat Sour Cream, Beans, Tomatoes');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4537cb56-314a-4316-b7ae-29d11bc290c7','cfe8cf1c-54e5-4f58-a0f4-09d16f8b169a','Cheesy Gordita Crunch',3.99,'https://www.tacobell.com/images/22813_cheesy_gordita_crunch_269x269.jpg','A warm flatbread layered with three-cheese blend and wrapped around a crunchy taco filled with seasoned beef, spicy ranch sauce, crispy lettuce and shredded cheddar cheese.','Seasoned Beef, 3 Cheese Blend, Lettuce, Spicy Ranch, Cheese');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4537cb56-314a-4316-b7ae-29d11bc290c7','d5a1f36a-d7a2-4285-a832-0d2f3b83ddab','Cheesy Fiesta Potatoes',1.69,'https://www.tacobell.com/images/22530_cheesy_fiesta_potatoes_269x269.jpg','The third cousin of Hollywood''s favorite vegetable socialite family; you may have already heard of cousins Cool Beans and the lesser known, Kooky Corn. Cheesy Fiesta Potatoes is known to throw some major A-list ragers at his house. Unlike those relatives of his, Fiesta Potatoes likes to keep a balance. The reduced-fat sour cream topping keeps it cool, but not pretentious cool like Cool Beans, who just sits in the corner and criticizes every band''s most recent record for being too well-produced. Cheesy Fiesta Potatoes is cool like sending invites to all his friends and always wanting to put others first and making sure everyone is having a good time at one of his parties. He''s cool because his parties are filled with the people you want to know in the industry. So, he often has up-and-coming bands perform at his parties in hopes to help them get discovered. He loves to be a helping hand to people. However, Fiesta Potatoes'' other topping, nacho cheese sauce, shows the wild side. How wild? Well, why don''t you ask yourself that same question, Johnny? How wild do you think the Cheesy Fiesta Potatoes gets? Imagine a rager of a party, but remember he knows all the A-listers in the industry so you know it begins classy and elegant but as the night goes on, it just gets out of hand. You''ll witness Crunchwrap Supreme® slide down the staircase. Quesarito cannonballing in the pool in his trunks (because he comes prepared when he parties) and he splashes everyone who is small-talking around the pool. Soft Taco will be chatting it up by the bonfire talking about her latest European excursion. But with all this wildness, it''s still not as wild as the perpetually unpredictable cousin Kooky Corn, who we still haven''t heard from since she went to Reno a few weeks ago...','Potatoes, Nacho Cheese Sauce, Reduced Fat Sour Cream');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4537cb56-314a-4316-b7ae-29d11bc290c7','d5a1f36a-d7a2-4285-a832-0d2f3b83ddab','Chalupa Supreme',3.39,'https://www.tacobell.com/images/22850_chalupa_supreme_269x269.jpg','You start with something completely ordinary and unexciting, but still something to be desired. Something you know is destined for greatness but it just needs that extra push to really make it mystical and supernatural. Then, you realize what that extra something is and you magically turn it into your favorite food after only a few seconds. That''s all, a few seconds. Oh, you don''t believe in magic, huh? Well, this just got awkward. Would you like a handful of cold potato shavings with your skepticism? No? How about potato chips? Exactly. Do you want this piece of bread shaped like a tire? Gross. Well how about a donut? Boom. Willing to walk away from the latest deep fried concoction at the county fair? Yeah, that''s what we thought. This is what you get with the Chalupa: beautiful witchcraft. All it''s magicalness in one perfect package. Take a traditional flatbread, something already awesome in its own right, and fry it. How does the saying go? Everything is better fried? Something like that, right. Or so we''re told. Once the flatbread is fried, you suddenly have a shell that mysteriously marries chewy and crispy; pure sorcery and pure perfection. Hold onto your wand because we''re not done yet. Fill the flatbread shell with seasoned beef, a three-cheese blend, lettuce, tomatoes, and reduced fat sour cream, and you get a Dante-esque culinary anomaly. You get the Chalupa Supreme. The only greater fried magic trick known to man is turning arbitrary dough splashes, into funnel cake. Now that is nothing short of a miracle. Neither is the Chalupa Supreme. Try one, we dare you. American Vegetarian Association certified Vegetarian food items, are lacto-ovo, allowing consumption of dairy and eggs but not animal byproducts. We may use the same frying oil to prepare menu items that could contain meat. Vegetarian and meat ingredients are handled in common, and cross contact may occur, which may not be acceptable to certain types of vegetarian diets. Neither Taco Bell®, our employees, nor our franchisees, nor the AVA assume any responsibility for such cross contact.','Seasoned Beef, Reduced Fat Sour Cream, Tomatoes, 3 Cheese Blend, Lettuce');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('4537cb56-314a-4316-b7ae-29d11bc290c7','d5a1f36a-d7a2-4285-a832-0d2f3b83ddab','Crunchwrap Supreme',3.99,'https://www.tacobell.com/images/22362_crunchwrap_supreme_269x269.jpg','The Crunchwrap Supreme® is a flour tortilla layered with seasoned beef, warm nacho cheese sauce, a crispy tostada shell, crispy lettuce, ripe tomatoes and topped with cool reduced fat sour cream all wrapped in our signature Crunchwrap fold and grilled to go.','Seasoned Beef, Reduced Fat Sour Cream, Tomatoes, Lettuce, Nacho Cheese Sauce');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('7abc1f9d-981e-47e1-b287-b9fbdbe08f37','21bc42ca-1e89-4f54-8e87-063940367b51','Spicy Crispy Chicken Sandwich',4.39,'https://www.mcdonalds.com/is/image/content/dam/usa/nfl/nutrition/items/hero/desktop/t-mcdonalds-spicy-crispy-chicken-sandwich.jpg','With our Spicy Pepper Sauce topping the southern style fried chicken fillet on a toasted potato roll, this sandwich was made for those who like it crispy, juicy, tender and hot. The Spicy Crispy Chicken sandwich has 530 calories. Check out all the Crispy Chicken Sandwiches. Order one today in the McDonald''s app.','Crispy Chicken Fillet, Potato Roll, Spicy Pepper Sauce, Crincle Cut Pickel');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('7abc1f9d-981e-47e1-b287-b9fbdbe08f37','21bc42ca-1e89-4f54-8e87-063940367b51','Big Mac',5.69,'https://www.mcdonalds.com/is/image/content/dam/usa/nfl/nutrition/items/hero/desktop/t-mcdonalds-Big-Mac.jpg','Mouthwatering perfection starts with two 100% pure beef patties and Big Mac® sauce sandwiched between a sesame seed bun. It''s topped off with pickles, crisp shredded lettuce, finely chopped onion and American cheese for a 100% beef burger with a taste like no other. It contains no artificial flavors, preservatives or added colors from artificial sources.* Our pickle contains an artificial preservative, so skip it if you like. There are 550 calories in a Big Mac®. Order one today with McDelivery®!','Big Mac Bun, Beef Patty, Shredded Lettuce, Big Mac Sauce, American Cheese, Pickle Slices');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('7abc1f9d-981e-47e1-b287-b9fbdbe08f37','21bc42ca-1e89-4f54-8e87-063940367b51','Quarter Pounder with Cheese',5.39,'https://www.mcdonalds.com/is/image/content/dam/usa/nfl/nutrition/items/hero/desktop/t-mcdonalds-Quarter-Pounder-with-Cheese.jpg','Each Quarter Pounder® with Cheese burger features a ¼ lb.* of 100% fresh beef that''s hot, deliciously juicy and cooked when you order. It''s seasoned with just a pinch of salt and pepper, sizzled on a flat iron grill, then topped with slivered onions, tangy pickles and two slices of melty American cheese on a sesame seed bun. Our QPC® contains no artificial flavors, preservatives or added colors from artificial sources. **Our pickle contains an artificial preservative, so skip it if you like.A Quarter Pounder® with Cheese has 520 Calories. Order one today with Mobile Order & Pay!','Beef Patty, Bun, American Cheese, Ketchup, Pickle Slices, Onion');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('7abc1f9d-981e-47e1-b287-b9fbdbe08f37','77c4d3b9-3f96-41b1-aaa1-739b597a8fa6','World Famous Fries',2.59,'https://www.mcdonalds.com/is/image/content/dam/usa/nfl/nutrition/items/hero/desktop/t-mcdonalds-fries-large.jpg','McDonald''s World Famous Fries® are made with premium potatoes such as the Russet Burbank and the Shepody. With 0g of trans fat per labeled serving, these epic fries are crispy and golden on the outside and fluffy on the inside. Best of all, you can get medium Fries for free every Friday with any $1 purchase, exclusively in the McDonald''s App. Grab our World Famous Fries® and pair with one of our classic McDonald''s Burgers today! There are 490 calories in a large McDonald''s fries. Order your fries today with McDelivery® or get them with curbside pickup using Mobile Order & Pay!','Potatoes, Salt');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('7abc1f9d-981e-47e1-b287-b9fbdbe08f37','77c4d3b9-3f96-41b1-aaa1-739b597a8fa6','Egg McMuffin',2.79,'https://www.mcdonalds.com/is/image/content/dam/usa/nfl/nutrition/items/hero/desktop/t-mcdonalds-Egg-McMuffin.jpg','Our Egg McMuffin® breakfast sandwich is an excellent source of protein and oh so delicious. We place a freshly cracked Grade A egg on a toasted English Muffin topped with real butter and add lean Canadian bacon and melty American cheese. There are 300 calories in an Egg McMuffin®. Pair it with a Premium Roast Coffee and pass the line when you use Mobile Order & Pay, only on the McDonald''s App!','English Muffin, Egg, Canadian Bacon, American Cheese, Salted Butter, Clarified Butter');
INSERT INTO menu_items(restaurant_uid,menu_uid,name,price,img,description,ingredients) VALUES('7abc1f9d-981e-47e1-b287-b9fbdbe08f37','77c4d3b9-3f96-41b1-aaa1-739b597a8fa6','Sausage Burrito',1.29,'https://www.mcdonalds.com/is/image/content/dam/usa/nfl/nutrition/items/hero/desktop/t-mcdonalds-Sausage-Burrito.jpg','The Sausage Burrito is McDonald''s Breakfast Burrito and is loaded with fluffy scrambled egg, pork sausage, melty cheese, green chiles and onion! It''s wrapped in a soft tortilla, making it the perfect grab and go breakfast. There are 310 calories in a McDonald''s sausage burrito. Order a McDonald''s Sausage Burrito using the McDonald''s App to Mobile Order & Pay.','Scrambled Egg Sausage And Vegetable Mix, Flour Tortilla, American Cheese');